import { expect, test } from "@playwright/test";

test("creates a themed skill, explores its context, launches and reloads it", async ({ page }) => {
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("/");
  await page.getByRole("button", { name: "New Project" }).click();
  await page.getByPlaceholder("/path/to/new/project...").fill(process.env.MINIONS_E2E_PROJECT);
  await page.getByPlaceholder("Project name (optional, defaults to folder name)").fill("Skill Library Journey");
  await page.getByRole("button", { name: "Create", exact: true }).click();
  await page.getByRole("button", { name: "Initialize Git & create first commit" }).click();
  await page.getByRole("tab", { name: "Canvas" }).click();
  await page.getByRole("button", { name: "Skills", exact: true }).click();
  const panel = page.locator('[data-dock-panel="skills"]');
  await panel.getByRole("button", { name: "New skill" }).click();
  const editor = page.getByRole("dialog", { name: "New Skill" });
  await editor.getByLabel("Name *", { exact: true }).fill("Release Scout");
  await editor.getByLabel("Description", { exact: true }).fill("Review release readiness and deployment risks.");
  await editor.getByLabel("Template *", { exact: true }).fill("Review {{target}} before release. Check tests and rollback steps.");
  await editor.getByRole("button", { name: /Appearance/ }).click();
  await editor.getByRole("searchbox", { name: "Search icons" }).fill("rocket");
  await editor.getByRole("button", { name: "Rocket", exact: true }).click();
  await expect(editor.getByRole("button", { name: "Rocket", exact: true })).toHaveAttribute("aria-pressed", "true");
  const saved = page.waitForResponse((response) => response.request().method() === "PUT" && response.url().includes("/skills") && response.ok());
  await editor.getByRole("button", { name: "Save", exact: true }).click();
  await saved;
  // The editor can dismiss the dock via the existing outside-click behavior.
  if (!(await panel.isVisible())) await page.getByRole("button", { name: "Skills", exact: true }).click();
  await panel.getByRole("searchbox", { name: "Search skills" }).fill("Release Scout");
  await panel.getByRole("button", { name: "View Release Scout" }).click();
  await expect(panel.locator('svg[data-minions-icon="rocket"]')).toBeVisible();
  await expect(panel.getByText("Review {{target}} before release. Check tests and rollback steps.")).not.toBeVisible();
  await panel.getByText("Instructions", { exact: true }).click();
  await expect(panel.getByText("Review {{target}} before release. Check tests and rollback steps.")).toBeVisible();
  await panel.getByText("Inputs", { exact: true }).click();
  await expect(panel.getByText("Target", { exact: true })).toBeVisible();
  await panel.getByRole("button", { name: "Launch with Release Scout" }).click();
  await expect(panel).not.toBeVisible();
  await expect(page.getByText("Release Scout", { exact: true }).first()).toBeVisible();
  await page.reload();
  await page.getByText("Skill Library Journey", { exact: true }).click();
  await page.getByRole("tab", { name: "Canvas" }).click();
  await page.getByRole("button", { name: "Skills", exact: true }).click();
  await panel.getByRole("button", { name: "View Release Scout" }).click();
  await panel.getByRole("button", { name: "More actions for Release Scout" }).click();
  await page.getByRole("menuitem", { name: "Edit skill" }).click();
  const edit = page.getByRole("dialog", { name: "Edit Skill" });
  await edit.getByRole("button", { name: /Appearance/ }).click();
  await expect(edit.getByRole("button", { name: "Rocket", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect(errors).toEqual([]);
});
